# Generated by Django 4.1.1 on 2023-04-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseMain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
