# Generated by Django 4.1.1 on 2023-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseMain', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
