# Generated by Django 4.1.1 on 2023-04-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseMain', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
