# Generated by Django 4.1.1 on 2023-04-04 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseMain', '0007_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=266)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseMain.userdetail')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
